### ISSUE TITLE
RTX list versions grouped by tool

### ISSUE THREAD

**Issue by deHelden** [jdx/rtx#1019]
asdf has really comfortable way of grouping extensions.
Grouping extensions could be a bit handy.

<img width="275" alt="image" src="https://github.com/jdx/rtx/assets/36229277/52d9e595-9696-4463-92f6-118d945f2a27">

may we consider this output for RTX?

**Comment by jdx** [comment]
This is actually bad since it doesn't work well with grep. What's wrong with `rtx ls`?

**Comment by deHelden** [comment]
> This is actually bad since it doesn't work well with grep. What's wrong with `rtx ls`?

Everything is great. it's just style preferences. we could leave it as is it. Still I respect you think about grep.
