### ISSUE TITLE
`rtx exec --install`

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1038]
there should be a way to both install and execute a tool so you can do something like this even if you don't already have node installed:

```
rtx exec --install node@latest -- node -v
```

open for ideas on the naming here

**Comment by jdx** [comment]
on second thought, I'm actually thinking this could just be the standard behavior

**Comment by ramnes** [comment]
@jdx Do you think it would make sense to have `mise exec node -- node -v` (without the `@20`) install `node@20` if `node = 20` is specified in the `.mise.toml`?

I'm trying to implement scripts that automatically install the tools with mise if they're not already installed, without having to specify versions in every one of these scripts (and thus update them everywhere when needed).

Both `mise install node && node ...` and `mise exec node -- node ...` do not work currently; only workaround I've found is `mise install node && mise x -- node ...`, but that seems a bit hackish to me. :)

Kinda related to #1572 and my comment there.
