### ISSUE TITLE
Minimum rust version in Cargo.toml should be updated from 1.65.0 to 1.72.0

### ISSUE THREAD

**Issue by Zelzahn** [jdx/rtx#1048]
**Describe the bug**
Build fails on a rust version lower than 1.72.0, while the Cargo.toml says: `rust-version = "1.65.0"`. Looking at the error message, it seems to be that 1.72.0 should be the new minimum supported version.
During the installation my version was 1.70.0 and upgrading to 1.74.0 fixed it.

**To Reproduce**
1. Use a Rust version older than 1.72.0
2. Try to install it

**Expected behavior**
The installation is done.

**Error message**

```
error[E0277]: `Sender<Result<T, ErrReport>>` cannot be shared between threads safely
   --> src/timeout.rs:14:17
    |
14  |           s.spawn(|| {
    |  ___________-----_^
    | |           |
    | |           required by a bound introduced by this call
15  | |             let result = f();
16  | |             // If sending fails, the timeout has already been reached.
17  | |             let _ = tx.send(result);
18  | |         });
    | |_________^ `Sender<Result<T, ErrReport>>` cannot be shared between threads safely
    |
    = help: the trait `std::marker::Sync` is not implemented for `Sender<Result<T, ErrReport>>`
    = note: required for `&Sender<Result<T, ErrReport>>` to implement `Send`
note: required because it's used within this closure
   --> src/timeout.rs:14:17
    |
14  |         s.spawn(|| {
    |                 ^^
note: required by a bound in `std::thread::Scope::<'scope, 'env>::spawn`
   --> /.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/scoped.rs:191:28
    |
191 |         F: FnOnce() -> T + Send + 'scope,
    |                            ^^^^ required by this bound in `Scope::<'scope, 'env>::spawn`

For more information about this error, try `rustc --explain E0277`.
```

**Comment by jdx** [comment]
are you sure? the following works for me on a mac. I wonder if this is a linux thing maybe? What command are you running?

```
rustup run 1.60.0 cargo install rtx-cli -f
```

**Comment by jdx** [comment]
that said, I think for some reason I'm just not able to reproduce this since I am pretty sure the issue is here: https://doc.rust-lang.org/stable/std/sync/mpsc/struct.Sender.html#impl-Sync-for-Sender%3CT%3E

which I should be able to easily fix

**Comment by jdx** [comment]
oh! I had homebrew screwing up my paths and it was always using 1.74, now I can repro and have a fix

**Comment by Zelzahn** [comment]
I tried with 1.60.0, this gave me the folowing error: `error: failed to compile `rtx-cli v2023.12.2`, intermediate artifacts can be found at /tmp/cargo-installqdP7MP` and when running the command with 1.70.0 I can reproduce the error.
