### ISSUE TITLE
add system-level config

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1064]
So in asdf they call the "global" config `~/.tool-versions`—which is special because it's used even outside of the home directory. In rtx I've retained this naming convention and behavior though using `~/.config/rtx/config.toml` instead.

However it was correctly pointed out to me this isn't actually "global" at all. It's a user config. A truly global config should be `/etc/rtx/config.toml` however this isn't supported by rtx. Adding that as an extra config would be trivial and probably a good idea, however I think it's a little confusing when we start talking about behavior.

This is an artifact of me really not thinking about multi-user setups since I really just don't use them much. Of course they have their place though. One I've actually ran into a few times is using the same config for root and a non-root user. You can do this today with `RTX_CONFIG_FILE=/etc/rtx/config.toml` or `RTX_CONFIG_DIR=/etc/rtx` though (kind of, you'll then not use your user config).

I think, painful as it might be, we should think about migrating away from calling ~/.config/rtx/config.toml the "global" config and maybe call it the "user" config—unless people have a better idea on naming.

This would mean we would need to change the following:

```
$ rtx use --global node@20 # modifies /etc/rtx/config.toml
$ rtx use --user node@20 # modifies ~/.config/rtx/config.toml
$ rtx use node@20 # modifies .rtx.toml
$ rtx use ---env staging node@20 # modifies .rtx.staging.toml (used if RTX_ENVIRONMENT=staging)
```

I have some concerns about how users would likely need to run rtx under sudo here because sudo often causes permission problems. It still feels more like the "correct" behavior though.

In terms of migration, this would be painful but I think it can be done. What I would do is first add `rtx use --user`, make it behave identically to `rtx use --global`, but show a warning when using `rtx use --global` notifying the user they need to start using `rtx use --user` instead for a few months before changing the behavior of `rtx use --global` to modify /etc. Perhaps it would also be useful to make some kind of config to opt-into /etc early too.

Thoughts? Do you find this useful?

**Comment by rawalplawit** [comment]
Please keep it as it is and instead add `system` as the system-wide config located in `/etc/rtx/config.toml` by default. [This is how git](https://git-scm.com/docs/git-config#Documentation/git-config.txt---system) also does it.

New flags can be added for system-wide config by `RTX_SYSTEM_CONFIG_DIR` and so on.

This would require almost no migration besides documentation changes.

**Comment by jdx** [comment]
this is done, though I should make it configurable
