### ISSUE TITLE
remove deprecated `missing_runtime_behavior` config

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1065]
See https://github.com/jdx/rtx/issues/735 for context, but broadly is deprecated, no longer documented, functionality that lets you configure what happens when a runtime is missing but I removed this when adding the `--yes` flag since it's a much easier method that more directly handles the use-case this was intended for (autoinstalling).

Since it's been undocumented, the next step should be to warn users that are relying on it, then schedule a time to remove the code for it. Unfortunately this setting is actually used internally in the codebase in a few places so that will need to first be refactored out.

Also, there was a change that made it so things passed into the CLI as arguments such as `rtx use node@20` will autoinstall and things just in config files will not. What's nice about this is rtx can behave more consistently across commands rather than where it was when some commands would autoinstall (`rtx use`/`rtx install`), but others would not (`rtx shell`/`rtx exec`).

This should be audited as well to make sure that this is working as I described everywhere (flags autoinstall, config tools do not except in the case of `rtx install`).

Also see https://github.com/jdx/rtx/issues/1065 where I mention that maybe `--yes` should only be a CLI flag and not a setting for security reasons.

**Comment by hwadii** [comment]
Hello! Thanks for this awesome project, love it!

I see that `missing_runtime_behavior` is now gone; is there any way to ignore runtime warnings now? Besides setting log level to a higher value.

**Comment by jdx** [comment]
for now I took out those warnings
