### ISSUE TITLE
unable to install hub with shorthand

### ISSUE THREAD

**Issue by jylenhof** [jdx/rtx#1076]
rtx install hub@latest
cloning https://github.com/vixus0/asdf-hub.git
loading plugin remote versions
rtx Failed listing remote versions for plugin hub
rtx error running list-all: exited with code 1

rtx Run with RTX_DEBUG=1 for more information

Solution 1 : use the forked repo which have a curl which follow links... So change the shorthand and don't take the one from asdf plugin list

jylenhof@pcportablejyl:~$ rtx plugin install hub https://github.com/claygorman/asdf-hub.git --force
uninstalling
removing /home/jylenhof/.local/share/rtx/plugins/hub
cloning https://github.com/claygorman/asdf-hub.git
loading plugin remote versions
https://github.com/claygorman/asdf-hub.git#71f6a13
jylenhof@pcportablejyl:~$ rtx install hub@latest
jylenhof@pcportablejyl:~$ 

Solution 2 : Fork the repo

**Comment by jdx** [comment]
this should go here https://github.com/asdf-vm/asdf-plugins

**Comment by jylenhof** [comment]
There's an open PR for this I did :

https://github.com/asdf-vm/asdf-plugins/pull/921
