### ISSUE TITLE
Add config setting for GitHub token for rate-limiting

### ISSUE THREAD

**Issue by liamdawson** [jdx/rtx#1078]
When I'm working from a shared location, I sometimes get errors that look like this:

```
[WARN] failed to resolve tool version: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/rbenv/ruby-build/releases/latest)
```

Following those up in the browser gives me the following message:

```json
{"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

I've noted that `rtx` will use a `GITHUB_API_TOKEN` in multiple places if that's been defined. This seems to resolve the errors. It'd be great if I could set that environment variable via config instead, so I don't have to either:

- Remember to set the environment variable when using `rtx`, or
- Worry about potential unintended effects on other applications that might check the same environment variable

**Comment by jdx** [comment]
now that https://rtx-versions.jdx.dev/ is being used I don't think this is necessary
