### ISSUE TITLE
[JAVA] file_type and image_type can be null

### ISSUE THREAD

**Issue by hkoosha** [jdx/rtx#1110]
**Describe the bug**
Java plugin fetches the file [joschi](https://joschi.github.io/java-metadata/metadata/all.json) from github.io, which has a json structure, which is an array of objects which have the properties `file_type` and `image_type`. From recently, these properties can be null. as in `"file_type": null` (`null` without quotation marks). Currently rtx does not expect these properties to be null and the `reqwest` deserializer fails.

**To Reproduce**
1. Install the latest rtx from master branch.
2. Run `rtx ls-remote java`.
3. You'll see it fails at line 370 in java.rs with unexpected token `null` while expecting a string.

**Expected behavior**
rtx should be able to handle this file with null values for `image_type` and `file_type`.

**`rtx doctor` output**

```text
rtx version:
  2023.12.18 linux-x64 (3eebf1e 2023-12-07)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Thu, 7 Dec 2023 17:44:45 +0000
  Rust Version: rustc 1.74.1 (a28077b28 2023-12-04)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2022 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx data directory:
  /home/.../.local/share/rtx

rtx environment variables:
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "plugin_autoupdate_last_check_duration": "7d", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:


No problems found
```

**Comment by jdx** [comment]
this occurred before I think, it was actually caused by some bad data in the metadata but we can still guard against it here
