### ISSUE TITLE
Can't install rtx at all

### ISSUE THREAD

**Issue by alanwilter** [jdx/rtx#1128]
Trying on Linux Ubuntu 20.04 x86_64

Right now, the standalone script is not working

```bash
install.sh: line 119: ${rtx_data_dir:}/bin/rtx: bad substitution
```
**To Reproduce**
```
curl https://rtx.pub/install.sh | sh

# or
gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0x29DDE9E0
curl https://rtx.pub/install.sh.sig | gpg --decrypt > install.sh
# ensure the above is signed with the rtx release key
sh ./install.sh
./install.sh: 169: Syntax error: Unterminated quoted string

bash ./install.sh
./install.sh: line 119: ${rtx_data_dir:}/bin/rtx: bad substitution
```

**Comment by jylenhofdecat** [comment]
install_path="${RTX_INSTALL_PATH:-${rtx_data_dir:}/bin/rtx}"

should probably be :

install_path="${RTX_INSTALL_PATH:-${rtx_data_dir}:/bin/rtx}"

**Comment by alanwilter** [comment]
Thanks, I ended up doing this.

**Comment by jdx** [comment]
I need to have the installer tested before it goes out, this isn't the first time something broke in it

**Comment by jdx** [comment]
oh I remember why I don't have a test for it. The install script contains the shasums for the to-be-released assets that aren't yet available. So the script can't actually function until _after_ the release is live.

I think I might be able to have a test for it if it reuses the old shasums though.
