### ISSUE TITLE
Using with .nvmrc

### ISSUE THREAD

**Issue by casey-speer** [jdx/rtx#1188]
Hi, I'm newer to `rtx` so maybe I'm confused about how to use the toolset, but I'm having trouble with my project's `.nvmrc`.

I've been trying:

`cd my_proj_dir_with_nvmrc`
`rtx use node` or `rtx use`

When I try to check the version using
`rtx local node`

it complains about no version being available in `.tool-versions`.

If I explicitly `rtx use node@x.x.x` then `rtx local node` will work as expected.

This is fine I suppose, but then I don't understand exactly how `.nvmrc` files are supported if neither `rtx use` nor `rtx local node` seem to understand them.

Here is the output of `rtx settings ls`:

```
always_keep_download = false
always_keep_install = false
asdf_compat = false
disable_default_shorthands = false
disable_tools = []
experimental = false
jobs = 4
legacy_version_file = true
legacy_version_file_disable_tools = []
plugin_autoupdate_last_check_duration = 7d
raw = false
trusted_config_paths = []
verbose = false
yes = false
```

Is there something I'm missing to get `rtx` to respect `.nvmrc` ?

**Comment by jdx** [comment]
rtx isn't able to write out to legacy files with `rtx use`. You'll need to just install the version you want and manually set the version by doing `echo "v21.4.0" > .nvmrc`. You should see it in `rtx config` and `rtx ls`.

**Comment by casey-speer** [comment]
@jdx ah I see. I think `nvm use` used to just read the `.nvmrc` and switch to the correct version when run without args. Looks like that's no longer the case so this makes sense. Thank you!
