### ISSUE TITLE
"rtx ls-remote java" lists non available version

### ISSUE THREAD

**Issue by thowimmer** [jdx/rtx#1196]
**Describe the bug**
`rtx ls-remote java` lists Azul Zulu OpenJDK builds which does not exists.

**To Reproduce**
* `rtx cache clean`
* `rtx ls-remote java | grep zulu-17.46.`
```
zulu-17.46.19
zulu-17.46.27
zulu-17.46.27_1
zulu-17.46.29
```

17.46.27, 17.46.27_1 and 17.46.29 does not exists - see:
https://www.azul.com/downloads/?version=java-17-lts&package=jdk&show-old-builds=true#zulu

Therefore the version upgrade fails as well:
* `rtx outdated java`
```
Tool    Requested  Current        Latest
java    zulu-17    zulu-17.46.19  zulu-17.46.29
```
* `rtx upgrade java`
```
rtx no metadata found for version zulu-17.46.29
rtx Run with RTX_DEBUG=1 for more information
```

**Expected behavior**
Only available versions should be listed with `ls-remote`.

**`rtx doctor` output**

```text
rtx version:
  2023.12.28 macos-arm64 (2023-12-15)

build:
  Target: aarch64-apple-darwin
  Features: DEFAULT, NATIVE_TLS
  Built: Fri, 15 Dec 2023 05:30:05 +0000
  Rust Version: rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

rtx data directory:
  /Users/.../.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh
  RTX_DEBUG=0

settings:
  {
    "experimental": true,
    "color": true,
    "always_keep_download": false,
    "always_keep_install": false,
    "legacy_version_file": true,
    "legacy_version_file_disable_tools": [],
    "plugin_autoupdate_last_check_duration": "7d",
    "trusted_config_paths": [],
    "verbose": false,
    "quiet": false,
    "asdf_compat": false,
    "jobs": 4,
    "shorthands_file": null,
    "disable_default_shorthands": false,
    "disable_tools": [],
    "raw": false,
    "yes": false
  }

config files:
  /Users/.../.config/rtx/config.toml

plugins:
  bun            (core)
  bundler        https://github.com/jonathanmorley/asdf-bundler.git#a461ac4
  cocoapods      https://github.com/ronnnnn/asdf-cocoapods.git#d45de04
  deno           (core)
  doctl          https://github.com/maristgeek/asdf-doctl.git#9344c6c
  doctoolchain   https://github.com/joschi/asdf-doctoolchain#d1f0169
  erlang         (core)
  git            https://gitlab.com/jcaigitlab/asdf-git.git#0bfd42e
  go             (core)
  helm           https://github.com/Antiarchitect/asdf-helm.git#a39e17b
  helmfile       https://github.com/feniix/asdf-helmfile.git#818feac
  java           (core)
  k6             https://github.com/grimoh/asdf-k6.git#8e65b77
  k9s            https://github.com/looztra/asdf-k9s.git#2b3af87
  kubectl        https://github.com/asdf-community/asdf-kubectl.git#cbe6df4
  kubectx        https://gitlab.com/wt0f/asdf-kubectx.git#8c0b4aa
  maven          https://github.com/halcyon/asdf-maven.git#625d6e5
  node           (core)
  python         (core)
  ruby           (core)
  starship       https://github.com/grimoh/asdf-starship.git#f546452

toolset:
  starship@latest, node@lts, maven@3.9.4, python@miniconda3-latest, kubectl@latest, kubectx@latest, java@zulu-17, k6@latest, k9s@latest, helm@latest, helmfile@latest, doctl@latest, doctoolchain@latest

No problems found
```

**Additional context**
It could well be that this is not related to rtx but the metadata repository.
How can I create a bugreport/pull-request there?

**Comment by jdx** [comment]
looks like this is the issue: https://github.com/joschi/java-metadata/blob/31243ba88296e68897cfbf194c077a3c088c64b6/docs/metadata/ga/linux/i686/jdk/hotspot/zulu.json#L3950

**Comment by thowimmer** [comment]
Hi @jdx,

thanks for the quick feedback!

I guess you're on the right track. However, I believe the following entries are causing the issue:
* [17.46.27](https://github.com/joschi/java-metadata/blob/31243ba88296e68897cfbf194c077a3c088c64b6/docs/metadata/ga/linux/aarch64/jre/hotspot/zulu.json#L1267)
* [17.46.27_1](https://github.com/joschi/java-metadata/blob/31243ba88296e68897cfbf194c077a3c088c64b6/docs/metadata/ga/linux/aarch64/jre/hotspot/zulu.json#L1267)
* [17.46.29](https://github.com/joschi/java-metadata/blob/31243ba88296e68897cfbf194c077a3c088c64b6/docs/metadata/ga/linux/aarch64/jre/hotspot/zulu.json#L1317)

I guess I should create a ticket in the https://github.com/joschi/java-metadata/ repository right?

**Comment by jdx** [comment]
it might be because of the version host, can you try this:

```
export RTX_USE_VERSIONS_HOST=0
rtx cache clear
```

if that's it, we can probably disable it for java

**Comment by jdx** [comment]
what I think might be happening is the set of versions for java are not the same across OS/arch. The asset host figures out what the java versions are and puts them here for rtx to use like a cache: https://github.com/jdx/rtx-versions/blob/main/docs/java

**Comment by thowimmer** [comment]
`export RTX_USE_VERSIONS_HOST=0` solved the issue 🥳  Many thanks!

```
❯ export RTX_USE_VERSIONS_HOST=0

~
❯ rtx cache clear
rtx cache cleared

~
❯ rtx outdated java
[INFO] All tools are up to date

~
❯ rtx upgrade java
[INFO] All tools are up to date
```

Would it be possible for rtx-versions to considered OS & arch?

**Comment by jdx** [comment]
> Would it be possible for rtx-versions to considered OS & arch?

possibly, but I think this might be specific to java. With java it already uses the metadata service so it's not a huge performance boost to use rtx-versions with that language. It's more helpful for projects that use the github api as that is often rate limited on shared hardware.

**Comment by jdx** [comment]
once I get some time to look at this I think we could maybe use rtx-versions for "quick" lookups  but when installing it could fetch the larger java metadata file and then use that as the source of truth. Something along those lines.

The thing about the [java metadata](https://rtx-java-metadata.jdx.dev/metadata/ga/linux/x86_64.json) is that it's really large. 4.7mb vs 65kb for the [versions metadata](https://rtx-versions.jdx.dev/java).

**Comment by jdx** [comment]
another idea is maybe I can modify the java metadata (I did fork it for this reason) and add smaller files that only contain the data I need, maybe even using messagepack to pack it down further

**Comment by thowimmer** [comment]
Many thanks for the quick feedback! Kudos for this awesome tool 👏🏼
