### ISSUE TITLE
rtx exec: pass signal to process

### ISSUE THREAD

**Issue by mustafa0x** [jdx/rtx#1234]
Before adding rtxx this would reload gunicorn. Now it stops the service.

```
ExecStart=rtxx poetry run gunicorn app:application
ExecReload=/usr/bin/kill -HUP $MAINPID
```

**Comment by jdx** [comment]
`rtx x` performs an exec, it doesn't launch a child process so there is nothing for rtx to pass signals to.

https://github.com/jdx/rtx/blob/f42fdd22cb89affe8dbb5950d7d890aa02126232/src/cli/exec.rs#L91

You can probably do the same in your rtxx script by running `exec rtx x` instead of just `rtx x`

**Comment by mustafa0x** [comment]
Thanks @jdx that seemed to fix, even though I didn't fully understand the problem (if exec, shouldn't signals be passed to poetry?), nor the solution (how does adding exec help?)! :)

Maybe I'll do some reading on exec.

**Comment by mustafa0x** [comment]
I've changed my service file to this. `kill -HUP` is stopping the service instead of reloading gunicorn. 

```
ExecStart=mise r prod
ExecReload=kill -HUP $MAINPID
```

`sudo service app status`:
```
● app.service
     Loaded: loaded (/etc/systemd/system/app.service; enabled; vendor preset: enabled)
     Active: active (running)
   Main PID: 682702 (mise)
```
