### ISSUE TITLE
tasks

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1249]
similar to arbitrary env vars, I'd like rtx to be able to execute arbitrary commands like a make replacement:

```toml
[tasks]
compile = "go build ./.."
test = "go test ./.."
clean = "rm -rf build"
```

Then run these with:

```
$ rtx run compile
```

I'm wondering if maybe putting this into the config under `[run]` or making the command `rtx task` might help unify these. Not sure though since I don't like the semantics of either of those much. I worry slightly about confusion between `rtx exec` and `rtx run` though.

Another thing I would like to make easy here would be "watching"—which I feel is a bit lacking in the community. I'm not really happy with any of the current file watchers around that I've used. Maybe this could be done with `rtx watch test` or `rtx run --watch test`.

kudos to @pepicrft for the idea here

**Comment by pepicrft** [comment]
This is fantastic @jdx. We'll adopt it in https://github.com/tuist/tuist, where we've used a Makefile just for that. 
The other thing that would be useful is activating and deactivating environment variables as you enter a project directory. For example, a Node project might want to set `NODE_ENV=development` by default. The interface could be something along the lines of:

```toml
[env]
NODE_ENV = "development"
```
Do you think this aligns with the responsibilities of rtx?

**Comment by jdx** [comment]
we already support that: https://github.com/jdx/rtx?tab=readme-ov-file#rtxtoml

**Comment by jdx** [comment]
that said, I think this is an example of just how unruly a single readme has become for a large project like rtx. I think if it was split up it might be easier to see things like this.

**Comment by pepicrft** [comment]
@jdx would you be up for moving the documentation to a documentation website? We can set it up with a tool like [VitePress](https://vitepress.dev) and deploy it to a platform like Netlify / Cloudflare / GitHub Pages. The upside of that is that we can then get can contact Algolia and get added to their open source program to have search for free.

**Comment by jdx** [comment]
yeah I think it's time to move on from the old readme
