### ISSUE TITLE
auto-installing

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1266]
there has been some basically accidental support for "autoinstalling" runtime versions with rtx. This wasn't something I fully thought out so the support and functionality was never great. I don't think it's even possible anymore.

With rtx's design this really has never seemed like a good fit to me. I don't think rtx should autoinstall a bunch of stuff just when you enter a directory. Forgetting the security risk I just think it would be extremely annoying to get "locked out" of your shell session while rtx might take tens of minutes to install something.

That said, after thinking about this and using cargo a lot, I do think the whole lazy-loading of dependencies idea is really solid. In cargo, if I update the Cargo.toml manifest and add/remove something—I never need to remember to run a command like `cargo install`. When cargo builds, it automatically updates the crates.

I think that's what I would like to see rtx behave more like. Not auto install when you enter a directory, but auto install when you attempt to use something and the version isn't right.

This is tricky for both `rtx activate` and shims—though with shims it's a bit easier.

Part of the problem with shims is I don't have a reliable way to know which shim goes to which plugin, in fact, multiple plugins could potentially use the same shim. In practice though, I don't think this should matter.  We could detect that you're running `python` and you don't currently have a matching version of python according to `.rtx.toml` so we fetch one when the `python` shim is launched.

Technically rtx won't know for sure that `python` will be contained in the updated version but I think we can make an educated guess here. If only one plugin in the system uses a particular shim we know what plugin we need to install.

Where it gets a little trickier is when not using shims. If you're using `rtx activate` then when you call "python" it's just going to access what's on your system or maybe nothing at all. I think one solution here is we could attach to the `command_not_found` bash/zsh hook. If we get that, and we have a shim that would've been able to autoinstall the right version we can just do that then.

What this won't help with is if there is something on the system though. If it just falls back to the "system" python I don't think there is much we can/should do.

**Comment by powerman** [comment]
Looks like `command_not_found_handler` in "activate" mode has no effect in current version. Is it supposed to do something or it's just a leftover after this removed feature?
