### ISSUE TITLE
`bin/post-plugin-update` script

### ISSUE THREAD

**Issue by Hypnotist1148** [jdx/rtx#181]
The post plugin update script is not used yet.
Also see: https://asdf-vm.com/plugins/create.html#bin-post-plugin-update

The environment variable `ASDF_PLUGIN_PATH` would also be important.

**Comment by jdxcode** [comment]
I haven't implemented these since I haven't seen a plugin that actually uses them. Do you know of one? It would be easier to test if I could run it against a real plugin vs just writing it to the spec.

I do have a spot for this though: https://github.com/jdxcode/rtx/blob/main/src/plugins/mod.rs#L168

**Comment by jdxcode** [comment]
this might actually have unintended consequences since I suspect plugins doing this are likely to execute asdf. They're not supposed to do that and I have workarounds in place for it, but it's likely going to be a source of problems.

**Comment by Hypnotist1148** [comment]
> I haven't implemented these since I haven't seen a plugin that actually uses them. Do you know of one? It would be easier to test if I could run it against a real plugin vs just writing it to the spec.

I don't remember any of the top of my head.

> this might actually have unintended consequences since I suspect plugins doing this are likely to execute asdf. They're not supposed to do that and I have workarounds in place for it, but it's likely going to be a source of problems.

Yes this could be a problem!

**Comment by jdxcode** [comment]
I suppose we'll just leave this open until someone can tell me where it's actually used

**Comment by Hypnotist1148** [comment]
Maybe add a label like "help wanted"
