### ISSUE TITLE
interactive command to update tools

### ISSUE THREAD

**Issue by leipert** [jdx/rtx#479]
[`yarn upgrade-interactive`](https://classic.yarnpkg.com/en/docs/cli/upgrade-interactive) is a nice command which allows to update dependencies in package.json to the latest version (within the current semver definition or to the latest release with `--latest`). It would be nice to have a similar command, for example, consider the following `.tool-versions`

```
nodejs 16.14.2
pdm    2.4.8
python 3.11.0
```

When running the command (e.g. `rtx update-interactive` or `rtx update`), I would expect to get an interactive input, which could look like this:

```
Choose which tools to update. (Press <space> to select)

nodejs

 ◯ 16.14.2  ❯  16.20.0
 ◯ 16.14.2  ❯  17.9.1
 ◯ 16.14.2  ❯  18.15.0
 ◯ 16.14.2  ❯  19.8.1

pdm

 ◯ 2.4.8    ❯  2.4.9
 ◯ 2.4.8    ❯  2.5.2

python

 ◯ 3.11.0   ❯  3.11.2
```

So it would allow me to update to the latest version within a minor / major or to the latest release in a higher major.

**Comment by jdxcode** [comment]
`rtx upgrade` is now a command so this could be added, maybe just as a flag `rtx upgrade --interactive`. We use [dialoguer](https://docs.rs/dialoguer/latest/dialoguer/struct.MultiSelect.html) in the project already which has support for this kind of UI. If someone wanted to help contribute this would be fairly straightforward—just look at the commands `src/cli/upgrade.rs` and `src/cli/outdated.rs`.
