### ISSUE TITLE
Flags do not work in nushell

### ISSUE THREAD

**Issue by unredundant** [jdx/rtx#514]
**Describe the bug**
Hey :wave: I have installed RTX and am trying to use it inside nushell, I have followed the install instructions, confirmed that the rtx config file is placed correctly and sourced in my nu config file.  However, once sourced, RTX no longer recognizes flags as valid.

```
❯ rtx -V
Error: nu::parser::unknown_flag

  × The `rtx` command doesn't have flag `-V`.
   ╭─[entry #16:1:1]
 1 │ rtx -V
   ·      ┬
   ·      ╰── unknown flag
   ╰────
  help: Available flags: --help, --help(-h). Use `--help` for more information.
```

**To Reproduce**
Setup nushell and RTX.  Try to run simple command like `rtx -V`.

**Expected behavior**
Flags should work.

**`rtx doctor` output**

```
❯ rtx doctor
rtx version:
build:
  Target: x86_64-unknown-linux-gnu
  Features: SELF_UPDATE
  Built: Sun, 23 Apr 2023 16:26:02 +0000
  Rust Version: rustc 1.68.2 (9eb3afe9e 2023-03-27)
  Profile: release

shell:
  nu
  0.78.0

rtx environment variables:
  RTX_SHELL=nu

settings:
  {"experimental": "false", "missing_runtime_behavior": "warn", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "trusted_config_paths": "[]", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /home/ryan/.config/rtx/config.toml

plugins:
  java   https://github.com/rtx-plugins/rtx-java.git#24706b7
  node   (core)
  yarn   https://github.com/twuni/asdf-yarn.git#376c540

toolset:
  java@17, node@20

No problems found
```

**Additional context**

Deleting this function from `~/.config/nushell/rtx.nu` seems to resolve the issue, but I am not sure if this has other unintended side effects.

```
def-env rtx [command?: string, --help, ...rest: string] {
  let commands = ["shell", "deactivate"]
  
  if ($command == null) {
    ^"/home/ryan/.cargo/bin/rtx"
  } else if ($command == "activate") {
    let-env RTX_SHELL = "nu"
  } else if ($command in $commands) {
    ^"/home/ryan/.cargo/bin/rtx" $command $rest
    | parse vars
    | update-env
  } else {
    ^"/home/ryan/.cargo/bin/rtx" $command $rest
  }
}
```

**Comment by kemitix** [comment]
I can confirm that I get the same error. In addition, I can't simply run `rtx doctor`, I have to use `~/.cargo/bin/rtx doctor`. If I'm using `~/.cargo/bin/rtx` then everything works as expected.

**Comment by Mouwrice** [comment]
Hi. I just came across the same issue. Has there any solutions been provided for this problem?

@robrecord the issue you mentioned is about permitting the use of a `--` (double dash) flag, but this issues does not provide a fix for these arguments that cannot be parsed.

Is there just something wrong with the activation script for the nushell or is this a nu issue?

**Comment by unredundant** [comment]
I'm not sure what side effects this may have... 

I did get this to work, by going into the rtx nu config (`~/.config/nushell/rtx.nu`) and changing the line `def-env rtx ...` to `def-env runtx`

So, less a solution, and more of a hack :) 

But I can at least now use RTX to install tools globally, which, is really all I personally use it to do

**Comment by Nezteb** [comment]
I'm hoping my PR fixes this. 🤞 https://github.com/jdx/rtx/pull/981

**Comment by Mouwrice** [comment]
> I'm hoping my PR fixes this. 🤞 #981

@Nezteb I just tested your PR and can confirm that it indeed resolved the issue, thanks! Let's hope that it gets approved and released soon :crossed_fingers:
