### ISSUE TITLE
Use globally default Node version when .nvmrc version is not available

### ISSUE THREAD

**Issue by Songggggr** [jdx/rtx#701]
![image](https://github.com/jdxcode/rtx/assets/131334123/5a564350-b56d-44aa-8ac1-bd6bfcdfc68f)
![image](https://github.com/jdxcode/rtx/assets/131334123/26dd8c94-fefc-4ee9-9ac4-52aab91dd800)
When I enter a directory that contains a .nvmrc file and I don't have the corresponding version installed, I receive a warning that Node is not available. I would like to use the globally default version instead of having no Node installed, even if the corresponding version is not available.

**Comment by jdxcode** [comment]
it doesn't make sense to me why it would behave this way. If the requested version is not available rtx shouldn't do anything

**Comment by jdxcode** [comment]
maybe you should just disable legacy file parsing for node: https://github.com/jdxcode/rtx#rtx_legacy_version_file_disable_toolsnodepython

**Comment by Songggggr** [comment]
@jdxcode I want to implement, if there's a node that matches, use a node that matches, if there's no node, just warn, but do nothing
