### ISSUE TITLE
rtx node: The subcommand 'node' wasn't recognized

### ISSUE THREAD

**Issue by dfang** [jdx/rtx#712]
**Describe the bug**

```
λ rtx node
rtx error: The subcommand 'node' wasn't recognized
rtx Run with RTX_DEBUG=1 for more information
```
but `rtx node -h` works.

it seems `node-build` is [updated automatically](https://github.com/jdxcode/rtx/blob/main/docs/node.md#updating-node-build-definitions) during my test, what is this subcommand for? maybe hide it from the list?

**To Reproduce**

```
λ rtx version
1.34.1 macos-x64 (76f8de3 2023-07-14)
```

**Comment by jdxcode** [comment]
`rtx node` is not a command but it has commands inside of it. This is working as expected.

**Comment by dfang** [comment]
at least make `rtx node` behaves like `rtx node -h`, not raising errors ?

**Comment by jdxcode** [comment]
I think that would be fine

**Comment by jdx** [comment]
the subcommand is going away as part of #1028 so I'm going to close this
