### ISSUE TITLE
raspberry pi / armv6l support

### ISSUE THREAD

**Issue by jedahan** [jdx/rtx#793]
What would be needed to add support for Raspberry Pi Zero W?

**Comment by jdxcode** [comment]
Does it not work? You should be able to install with cargo

**Comment by jedahan** [comment]
cargo install does not work

trying cargo build --release but the last step fails.

I think it might be running out of memory. I'll try increasing swap but would love to know if there's a way to confirm this suspicion.

**Comment by jdx** [comment]
there should now be precompiled binaries you can use
