### ISSUE TITLE
About 2023.8.10 release

### ISSUE THREAD

**Issue by chenrui333** [jdx/rtx#861]
👋 it looks like 2023.8.10 was not completed ([some jobs failed](https://github.com/jdx/rtx/actions/runs/6038049007/job/16383967305)). Raise this issue for some awareness. Thanks!

relates to Homebrew/homebrew-core#140996

**Comment by jdx** [comment]
oh thank you for pointing that out! I hadn't noticed

**Comment by chenrui333** [comment]
thanks @jdx !
