### ISSUE TITLE
Avoid installing runtime version when trying to set local

### ISSUE THREAD

**Issue by x80486** [jdx/rtx#867]
## Describe the Bug

Say I have these runtimes installed:

```shell
$ rtx list 
java       temurin-8.0.382+5
java       temurin-11.0.20+8
java       temurin-17.0.8+7 (outdated) ~/.config/rtx/config.toml temurin-17
```

If I do `rtx local java@temurin-11`, I would expect `rtx` to try to reuse the current version I have installed, rather than installing the latest version and then setting it.

## To Reproduce

- Install `rtx` version `2023.8.2`
- Install `java` plugin and version `temurin-11.0.20+8`
- Try to set the runtime version in a sub-directory using `rtx local java@temurin-11`

## Expected Behavior

`rtx` should reuse version `temurin-11.0.20+8` (already installed), rather than installing the latest version and then setting it.

## rtx doctor

```shell
$ rtx doctor 
rtx version:
  2023.8.2 linux-x64 (2023-08-24)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Thu, 24 Aug 2023 10:56:29 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx data directory:
  /home/x80486/.local/share/rtx

rtx environment variables:
  RTX_CONFIG_FILE=/home/x80486/.config/rtx/config.toml
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "false", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "0", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/x80486/.config/rtx/config.toml

plugins:
  java            https://github.com/rtx-plugins/rtx-java.git#a842ac6
  node            (core)
  python          (core)
  ruby            (core)

toolset:
  java@temurin-17

1 problem found:
new rtx version 2023.8.10 available, currently on 2023.8.2
```

**Comment by jdx** [comment]
so `rtx local` is a hidden command retained for asdf compatibility, in general I support `rtx use` more. I believe this was fixed but may still be problematic due to https://github.com/jdx/rtx/issues/928

closing for now but happy to reopen if there are still issues

**Comment by x80486** [comment]
OK, I was under the impression that if there is a version already installed, say `Java Temurin 11.x` and I request the same in a given location via `rtx use java@temurin-11`, `rtx` should use that one without checking if there is a new version.
