### ISSUE TITLE
Virtual environments created by rtx are bound to the python patch version

### ISSUE THREAD

**Issue by sbidoul** [jdx/rtx#877]
**Describe the bug**

Virtual environment created by rtx are bound to the python patch version.
This is somewhat annoying because upgrading python and pruning previous patch releases breaks existing virtual environments.

**To Reproduce**

Create a `.rtx.toml` like so

```
[tools]
python = {version='3.11', virtualenv='~/.virtualenvs/myvenv'}
```

`python` in `~/.virtualenvs/myvenv/bin/` is a symlink to `/home/me/.local/share/rtx/installs/python/3.11.5/bin/python` (notice 3.11.5).

**Expected behavior**

It should be a symlink to `/home/me/.local/share/rtx/installs/python/3.11/bin/python` (notice 3.11).

**`rtx doctor` output**

```
rtx version:
  2023.9.0 linux-x64 (f333ac5 2023-09-05)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Tue, 05 Sep 2023 14:17:19 +0000
  Rust Version: rustc 1.71.1 (eb26296b5 2023-08-03)
  Profile: release

shell:
  /usr/bin/fish
  fish, version 3.6.1

rtx data directory:
  /home/me/.local/share/rtx

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/me/.tool-versions
  /home/me/FOSS/pip-deepfreeze/.rtx.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  python@3.11, node@lts

No problems found

```

**Additional context**

Running `/home/me/.local/share/rtx/installs/python/3.11/bin/python -m venv` creates a venv symlinked to the expected python minor version.

Thanks for this great tool!

**Comment by jdx** [comment]
I sketched a more generic solution to this in https://github.com/jdx/rtx/issues/1059

**Comment by sbidoul** [comment]
Nice. Thanks!
