### ISSUE TITLE
Let `rtx ls --json` always return an array

### ISSUE THREAD

**Issue by pdecat** [jdx/rtx#882]
A tool is installed, it returns an array:
```
# rtx ls vault --current --json
[
  {
    "version": "1.14.2",
    "requested_version": "1.14.2",
    "install_path": "/home/patrick/.local/share/rtx/installs/vault/1.14.2",
    "source": {
      "type": ".tool-versions",
      "path": "/home/patrick/.tool-versions"
    }
  }
]
```

When a tool isn't, it returns an object:
```
# rtx ls tflint --current --json
{}
```

That makes the output json hard to process with other tools like jq.
Always returning an array would help with that.

**Comment by booniepepper** [comment]
Proposing a change here #896 

`rtx ls --json` will continue to return a `{ "plugin": [ ...runtimes ] }` structure

`rtx ls <plugin> --json` will only ever return a `[ ...runtimes ]` list (even if it's empty)
