### ISSUE TITLE
Support installation with cargo binstall

### ISSUE THREAD

**Issue by yodatak** [jdx/rtx#884]
Many rust tool are downloadable with cargo bininstall i can be interesting to support the installation of program with cargo binstall

https://github.com/cargo-bins/cargo-binstall
what do you think ?

**Comment by yodatak** [comment]
It not realy what i need like i want to have a list like i want like 
the latest ripgrep
the latest jetp
and to install them from cargo binstall not sure if explain well ^

**Comment by jdx** [comment]
it sounds like you just want to use rtx as a generic `cargo binstall` utility?

**Comment by yodatak** [comment]
Yes exactly to permit some cool program to be installed like rt does

**Comment by jdx** [comment]
I'm going to close as a duplicate of #580
