### ISSUE TITLE
Documentation: add a section how to work / switch with asdf and rtx

### ISSUE THREAD

**Issue by muescha** [jdx/rtx#906]
I noticed there's a missing section in the documentation regarding how to use and switch between asdf and rtx. My questions, which I believe should be addressed in the documentation, are:

### 1) Is it possible to use rtx and asdf simultaneously? 

I've noticed there's an alternative method for accessing the binaries - changing the path versus using shims. I'm unsure if it's possible to have both methods.)

### 2) Can I activate asdf or rtx on a per-folder basis? 
Is it feasible to use asdf for some folders and rtx for others?

### 3) Switching between systems 

What are the steps involved in transitioning from asdf to rtx, and rtx to asdf?

**Comment by jdx** [comment]
I would strongly discourage using asdf alongside rtx. It's technically possible by swapping out the shims directory. However if you're not able to figure out how to do that from that simple description you probably shouldn't bother and even if you do, I still don't think it's a good idea. I use both for testing but even for me it's an extremely confusing setup to deal with.

To my knowledge there isn't any functionality that asdf offers that rtx doesn't so this shouldn't be necessary.

As far as migrating, there isn't anything special you need to do if you're coming from asdf. Just install rtx like a new user and it will work with your existing .tool-versions files.

**Comment by muescha** [comment]
thx for your answer

note to me:
I should read the manual complete - I found the migration section: https://github.com/jdx/rtx#how-do-i-migrate-from-asdf

**Comment by muescha** [comment]
> note to me: I should read the manual complete - I found the migration section: [jdx/rtx#how-do-i-migrate-from-asdf](https://github.com/jdx/rtx#how-do-i-migrate-from-asdf)

Once more, I got lost in the lengthy readme. I've made the PR #1013 with tips for asdf users transitioning over.
