### ISSUE TITLE
Cannot use rtx wit appimages - How would I make this work?

### ISSUE THREAD

**Issue by cocoonkid** [jdx/rtx#921]
In this case it's the cursor editor (a vscode derivative).

```
[🔴] × RTX_DEBUG=1 rtx list            
[DEBUG] rtx::config: Files: ~/Documents/xxxx/data_projects/xxx/xxx/.tool-versions, ~/.rtx.toml
Installed Plugins: assh, direnv, poetry, rust
Error: 
   0: cursor-0.11.8_ac870972f80c2ffcb576280407f9db92.AppImage is not a valid shim

Location:
   src/shims.rs:67

Version:
   2023.9.2 linux-x64 (e49575f 2023-09-28)

Suggestion: Run with RTX_DEBUG=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

So for example the poetry command is not available.

Thanks for looking into this. I usually do not  use appimages but some projects I use do :)

**Comment by jdx** [comment]
I'm not clear on what it is you're actually trying to do. For some context, what is happening here is the binary isn't named "rtx", in that case rtx assumes it is a shim and attempts to call the underlying tool: https://github.com/jdx/rtx/blob/main/src/shims.rs#L28-L30

Perhaps there is a way we can alter that logic.

**Comment by cocoonkid** [comment]
My apology for taking so long to reply.

I am using https://cursor.so/  and I get the following error when opening a terminal.

```
rtx cursor-0.14.0-build-231102m6tuamwbx_e882239ff71d2d2f8fad7f366fedb5ee.AppImage is not a valid shim
rtx Run with RTX_DEBUG=1 for more information
```

I tried adding /home/cocoonkid/.local/share/rtx/installs/node/20.8.0/bin/ as executable in the settings but no dice.


```
[🔍] × which npm
/usr/bin/npm
```
But when I open a regular terminal:


 ╰─λ rtx list
assh   2.16.0          ~/.rtx.toml      latest
direnv 2.32.3          ~/.rtx.toml      latest
java   21.0.0          ~/.tool-versions 21.0.0
node   20.8.0 (outdated) ~/.rtx.toml    latest
poetry 1.6.1 (outdated) ~/.rtx.toml     latest
python 3.9.18          ~/.rtx.toml      3.9.18
python 3.11.5
rust   1.73.0          ~/.rtx.toml      latest
Python virtualenv project detected. Run mkvenv to setup autoswitching
Time: 0h:00m:08s

 ╭─cocoonkid@arch in ~ via  v20.8.0 via  v3.9.18 took 7s
 ╰─λ which npm
**/home/cocoonkid/.local/share/rtx/installs/node/20.8.0/bin/npm**

**Comment by vinismarques** [comment]
@jdx I'm running version 2024.4.8-1 on Arch and if I understood correctly, it should be fixed in this version. Should I configure mise in a specific way to avoid this problem with AppImage? I'm using Cursor here as well, similar to OP.

**Comment by jorgeavaldez** [comment]
i'm running into the same issue when using cursor on manjaro
