### ISSUE TITLE
`rtx use` pollutes the environment

### ISSUE THREAD

**Issue by Slotos** [jdx/rtx#931]
Calling `rtx use` leaves an `.rtx.toml` file with no easily discoverable way to disable this behaviour.

### To Reproduce

`rtx use node@lts`

### Expected behavior

- `rtx use` merely updates the path for current session
- `rtx use --commit` _(naming is hard)_ behaves the way `rtx use` behaves now
- `rtx use --pin` behaviour is unchanged

#### `rtx doctor` output

```
rtx version:
  2023.10.1 macos-x64 (19220e5 2023-10-05)

build:
  Target: x86_64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Thu, 5 Oct 2023 00:29:48 +0000
  Rust Version: rustc 1.72.1 (d5c2e9c34 2023-09-13)
  Profile: release

shell:
  /usr/local/bin/fish
  fish, version 3.6.1

rtx data directory:
  /Users/-/.local/share/rtx

rtx environment variables:
  RTX_SHELL=fish

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /Users/-/.config/rtx/config.toml

plugins:
  elixir   https://github.com/asdf-vm/asdf-elixir.git#588ee99
  erlang   https://github.com/asdf-vm/asdf-erlang.git#267f6bb
  go       https://github.com/kennyp/asdf-golang.git#21d9c32
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  python@3.11 python@3.12, elixir@latest, erlang@latest, ruby@3.2.2, go@latest, node@20.7.0

No problems found
```

### Additional context

I often change tools versions when working with data, dpoing benchmarks, or simply fooling around. Having those sessions attempts change my environment from an expected default config was a surprise.

### Notes

Local transient environment would need to be consistently applied over the changes that arrive through version files updates:

> After activating, every time your prompt displays it will call rtx hook-env to fetch new environment variables. This should be very fast. It exits early if the directory wasn't changed or .tool-versions/.rtx.toml files haven't been modified.

While this can be confusing when I go and updates my versions configuration in a separate session, that would be my responsibility to figure out.

**Comment by jdx** [comment]
You're looking for `rtx shell`

**Comment by Slotos** [comment]
I absolutely do.

Second time I find an "issue", and second time `rtx` delivers a perfect solution out of the box. In other words, thank you!
