### ISSUE TITLE
Feat: Explicit reuse of openssl from /usr/local

### ISSUE THREAD

**Issue by spiffcs** [jdx/rtx#938]
## Summary

👋 Thanks for the awesome tool and experience!

When I went to install `Python-3.12.0` I noticed the following logs:
```
Downloading openssl-3.1.2.tar.gz...
-> https://www.openssl.org/source/openssl-3.1.2.tar.gz
Installing openssl-3.1.2...
Installed openssl-3.1.2 to /Users/user/.local/share/rtx/installs/python/3.12.0
```

It is awesome the tool handles this for users without openssl already installed.

However on my system I already had 3.1.2 installed. This lead to a couple of questions:
  1) I was wondering if the tool is always expected to install runtime dependencies to the `.local` path. I read through the dependency [docs](https://github.com/jdx/rtx/blob/main/docs/python.md) for python and assumed the dependencies specified [here](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) would be reused
  2) WDYT of a config option where paths/sources for runtime dependencies can be explicitly set. In this case openssl for python.

This might all be for nothing if what I saw was an extension of how [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) manages installing dependencies. If so please feel free to close the issue and thanks again for the awesome tool!

Also apologies if this is already handled in the config.

**Comment by jdx** [comment]
> This might all be for nothing if what I saw was an extension of how [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) manages installing dependencies. If so please feel free to close the issue and thanks again for the awesome tool!

right, python-build installs openssl, not rtx
