### ISSUE TITLE
Plugin uninstall silently removes installed tools

### ISSUE THREAD

**Issue by uvlad7** [jdx/rtx#942]
**Describe the bug**
If you install a plugin for a tool that already has a core plugin, such as Ruby, and you already have versions installed, and that try to remove that plugin, it removes all the setup without any warning.  

**To Reproduce**
Install tool
`rtx install ruby@2.7.8`
install plugin for Ruby
`rtx plugin install ruby https://github.com/asdf-vm/asdf-ruby.git`
then uninstall it
`rtx plugins uninstall ruby`
It just prints `rtx ruby uninstalled`, that's all, all you Ruby setup has gone.
I assume the same happens in case of other tools, that don't have a core plugin for them.

**Expected behavior**
Be able to remove plugin to roll back to the core one, or at least get a warning that all the versions installed will be removed with request to continue or abort.

**`rtx doctor` output**

```
rtx version:
  2023.9.1 linux-x64 (2023-09-13)

build:
  Target: x86_64-unknown-linux-gnu
  Features: BREW, DEFAULT, NATIVE_TLS
  Built: Wed, 13 Sep 2023 14:20:42 +0000
  Rust Version: rustc 1.72.0 (5680fa18f 2023-08-23) (Homebrew)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx data directory:
  /home/vladimir/.local/share/rtx

rtx environment variables:
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/vladimir/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  pipenv   https://github.com/and-semakin/asdf-pipenv.git#06a3181
  poetry   https://github.com/asdf-community/asdf-poetry.git#2f04828
  python   (core)
  ruby     (core)
  rust     https://github.com/asdf-community/asdf-rust.git#8436012

toolset:
  ruby@3.0.2, python@3.10.12 python@2.7.18, node@12.22.9, go@1.20.4, pipenv@2023.10.3, poetry@1.6.1, rust@1.72.1

1 problem found:
new rtx version 2023.10.1 available, currently on 2023.9.1

```

**Comment by jdx** [comment]
This isn't a bug, this is the intended behavior—though I agree it's not obvious. It's like this to avoid using a different plugin entirely. Reflecting on that a bit though I might have been a bit too "safe" by adding that logic since it's not terribly likely someone would reuse a completely different plugin.

I'm not sure what the repercussions would be right now, but I'm thinking we could just remove the logic that removes installs on plugin install/remove. I'm also not entirely sure how much work that would be.
