### ISSUE TITLE
Cannot activate virtualenv while using rtx python in fish shell, using the virtualenv activation file

### ISSUE THREAD

**Issue by oidualc** [jdx/rtx#943]
**Describe the bug**
Cannot activate virtualenv while using rtx python in fish shell, using the virtualenv activation file `.venv/bin/activate.fish`.

**To Reproduce**
- Use fish shell
- Use rtx (`rtx activate fish | source` at the end of `$HOME/.config/fish/config.fish` file
- Move to a new directory $HOME/test-venv
- Create a new virtualenv `python -m venv .venv`
- Activate it `source ./.venv/bin/activate.fish`

**Expected behavior**
The virtualenv gets activated, i. e. `which python` output is `/Users/user/test-venv/.venv/bin/python`

**Actual behavior**
The virtualenv does not get activated, i. e. `which python` output is `/Users/user/.local/share/rtx/installs/python/3.12.0/bin/python`

**`rtx doctor` output**

```
rtx version:
  2023.10.1 macos-arm64 (2023-10-05)

build:
  Target: aarch64-apple-darwin
  Features: BREW, DEFAULT, NATIVE_TLS
  Built: Thu, 5 Oct 2023 00:46:47 +0000
  Rust Version: rustc 1.72.1 (d5c2e9c34 2023-09-13) (Homebrew)
  Profile: release

shell:
  /opt/homebrew/bin/fish
  fish, version 3.6.1

rtx data directory:
  /Users/user/.local/share/rtx

rtx environment variables:
  RTX_SHELL=fish
  RTX_USE_TOML=1

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "true", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /Users/user/.config/rtx/config.toml

plugins:
  bun       (core)
  deno      (core)
  go        (core)
  haskell   https://github.com/asdf-community/asdf-haskell.git#6b66231
  java      https://github.com/rtx-plugins/rtx-java.git#24706b7
  node      https://github.com/rtx-plugins/rtx-nodejs.git#da3fc45
  python    https://github.com/rtx-plugins/rtx-python.git#2b29b16
  ruby      (core)

toolset:
  java@21, python@3.12, node@system

No problems found
```

**Additional context**
The virtual env gets activated using the .rtx.toml file inside the directory:

```toml
[tools]
python = {version="3",virtualenv=".venv"}
```

**Comment by jdx** [comment]
rtx dynamically changes your PATH to put its python runtime first. It really doesn't have a great way to detect that it shouldn't do that in this case. For example, what happens if you change directories into one that has an `.rtx.toml` file—should it modify the python runtime or not?

If you want to be more precise you'll need to use shims instead.

**Comment by oidualc** [comment]
Ok it makes sense, using the shims gives me the behaviour I was expecting, I'm closing this issue.
Just a piece of advice: I would add a section about this in the FAQ of the README.md. It's not a very intuitive behaviour without knowledge of how rtx works, and at the end of the day what an user sees is just the common way of activating a Python virtual environment not working.
