### ISSUE TITLE
Central source of truth

### ISSUE THREAD

**Issue by ShalokShalom** [jdx/rtx#950]
Is there already functionality in place, that does what this plugin does?
https://github.com/asdf-community/asdf-plugin-manager

If already present, consider mention that in the README 🙂

**Comment by jdx** [comment]
I don't know, it's not my project

**Comment by ShalokShalom** [comment]
Well, I guess you can read?

**Comment by jdx** [comment]
I think I misunderstood, I think we support all of this with the `[plugins]` section of .rtx.toml: https://github.com/jdx/rtx#rtxtoml

**Comment by ShalokShalom** [comment]
Thanks a lot. Do you consider this worthwhile to be included in the documentation/READEME?
As it is a feature, that is undocumented, as of now.
