### ISSUE TITLE
[Question] How does RTX figures the LTS version in Node.js?

### ISSUE THREAD

**Issue by x80486** [jdx/rtx#956]
I installed `Node.js` using `rtx use --global node@lts` and it installed version `18.18.2` — the current _maintenance_.

The current `active LTS` release is `20.8.1` 🤔

Is this something built within the `core` plugin for `Node.js`?

**Comment by steveno** [comment]
There's a conf file that stores it.

https://github.com/jdx/rtx/blob/main/src/cli/alias/snapshots/rtx__cli__alias__set__tests__alias_set.snap

As you can see node is still set to 18.

**Comment by x80486** [comment]
Not sure if there is an API for this, but I guess it could be better to make this dynamic :thinking:

**Comment by itehaxx** [comment]
> As you can see node is still set to 18.

see #946 instead

**Comment by sirajulm** [comment]
@jdx Does this mean I will have to reinstall the rtx each time to get the new `lts` version? 
Currently my lts still point to 18.15.0.
Now can I make 20 as the lts?
`rtx install node@lts` does not help. Neither does `rtx install node@20` changes the lts.

**Comment by lx4r** [comment]
Hmmm, for me it's not, even with the most recent version at the time of writing (`2023.11.9 linux-x64 (6616e5a 2023-11-29)`). When running `rtx install node@lts` I'm still getting Node.,js v18:

```

❯ rtx install nodejs@lts
Downloading node-v18.18.2-linux-x64.tar.gz...
-> https://nodejs.org/dist/v18.18.2/node-v18.18.2-linux-x64.tar.gz
WARNING: node-v18.18.2-linux-x64 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.
Installing node-v18.18.2-linux-x64...
Installed node-v18.18.2-linux-x64 to /home/lx4r/.local/share/rtx/installs/node/18.18.2
rtx node@18.18.2                                                                                                   ✓ 8s
```

**Comment by lx4r** [comment]
@x80486 @jdx Thanks, I was able to fix it now. First I unsuccessfully tried to uninstall the plugin:

```
❯ rtx uninstall plugin node
The application panicked (crashed).
Message:  no versions found
Location: src/cli/uninstall.rs:67

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

That led to the plugin not showing up in `rtx doctor`'s output anymore but no `node` plugin being listed when executing `rtx plugin ls --core`. However, after also doing a `rm -rf ~/.local/share/rtx/plugins/node` everything now works as expected 🙂 

Was there a way I could've noticed that the `rtx-node` plugin was deprecated?

**Comment by jdx** [comment]
I should probably add a warning—or just autoremove rtx-node
