### ISSUE TITLE
completions should complete plugins + versions

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#97]
the completions right now only help complete things like command names and option names.
Ideally you should be able to complete with something like this:

```
rtx install nodejs@18<tab><tab>
rtx install nodejs@<tab><tab>
rtx install nod<tab><tab>
```

This probably is non-trivial, but it would certainly be nice.

EDIT: this is working now, but some improvements can be made (I would welcome some help!)

![2023-12-07 14 07 07](https://github.com/jdx/rtx/assets/216188/6d8d6317-efd9-47df-913f-05bb4b525da6)

- [x] zsh
- [x] fish
- [x] zsh+fish `rtx uninstall` should only show installed versions (perhaps other commands as well)
- [x] fish's output can be improved, right now `rtx install <tab><tab>` starts off showing ancient bun versions. (see my comment about this below)
- [x] `rtx settings set <tab><tab>`

**Comment by Stanislav-Lapata** [comment]
Thanks for your great work

I think you can add this lines to fish completions
It adds completion for plugins and versions.
```fish
function __fish_rtx_list_all -a plugin
    rtx ls-remote $plugin 2>/dev/null
end

function __fish_rtx_arg_at -a number
    set -l cmd (commandline -opc)
    echo $cmd[$number]
end
set -l plugin_commands current global install latest local ls ls-remote prune uninstall # etc.
complete -c rtx -n "__fish_seen_subcommand_from $plugin_commands" -f -a '(rtx plugins)'
complete -c rtx -n '__fish_seen_subcommand_from (rtx plugins)' -f -a '(__fish_rtx_list_all (__fish_rtx_arg_at 3))'
```
![image](https://github.com/jdxcode/rtx/assets/12072329/cf490bd8-fad7-4581-ae37-9da103bb4ad3)
![image](https://github.com/jdxcode/rtx/assets/12072329/3c40d42e-916f-43f2-81f5-60493197e972)

It has few bugs but I don't know how I should fix them because I have never written completions
![image](https://github.com/jdxcode/rtx/assets/12072329/0654f28b-bcb3-4567-adf7-24a972f12e05)
![image](https://github.com/jdxcode/rtx/assets/12072329/7485aab4-a01f-4c0d-9dc6-0889cc3aed96)

**Comment by jdxcode** [comment]
looks promising, if I can find some time to have a deeper look I can check more. I like how simple this is for fish!

**Comment by jdx** [comment]
ok I got this working for zsh. I'll do it for fish too but not the other shells (these are a massive pain to write)

**Comment by fgimian** [comment]
> ok I got this working for zsh. I'll do it for fish too but not the other shells (these are a massive pain to write)

I think Bash really the common shell so it would be awesome if that could be supported in time too. 😄

**Comment by MrGreenTea** [comment]
> > ok I got this working for zsh. I'll do it for fish too but not the other shells (these are a massive pain to write)
> 
> I think Bash is really the most common shell so it would be awesome if that could be supported in time too. 😄

You are free to open a PR for this and implement it. Maybe @jdx will merge it with a disclaimer that they won't support it 😄

**Comment by AlecRust** [comment]
Zsh is the default on macOS and the most common shell by this point.

https://www.warp.dev/state-of-the-cli-2023#shell-preferences-and-personalizations

**Comment by jdx** [comment]
fish is a bit ugly unfortunately because I can't figure out how to separate the plugin from the version like with zsh
![CleanShot_2023-12-07_at_14 05 472x](https://github.com/jdx/rtx/assets/216188/9e1c84d2-06a1-4881-95e3-f764b3e7fde9)

I think this can be improved by changing it to be non-alphabetically ordered and showing results without versions first

**Comment by Stanislav-Lapata** [comment]
@jdx  Thanks for your excellent project
I think cache is unneeded here because after uninstalling I see deleted versions
https://github.com/jdx/rtx/blob/v2023.12.26/src/shell/completions/fish_complete.rs#L41-L43

```bash
❯ rtx ls --installed | awk '{print $1 "@" $2}'
elixir@1.15.4-otp-26
elixir@1.15.5-otp-26
elixir@1.15.7-otp-26
elixir@1.16.0-rc.1-otp-26
erlang@26.0.2
...

❯ rtx uninstall elixir@1.16.0-rc.1-otp-26
rtx elixir@1.16.0-rc.1-otp-26 uninstalled

❯ rtx ls --installed | awk '{print $1 "@" $2}'
elixir@1.15.4-otp-26
elixir@1.15.5-otp-26
elixir@1.15.7-otp-26
erlang@26.0.2
...
```
but
```bash
❯ rtx uninstall elixir@<tab><tab>
…lixir@1.15.4-otp-26  (Tool(s) to remove)  
…lixir@1.15.5-otp-26  (Tool(s) to remove)  
…lixir@1.15.7-otp-26  (Tool(s) to remove)  
…lixir@1.16.0-rc.1-otp-26  (Tool(s) to remove)
```
Last version is uninstalled

**Comment by jdx** [comment]
@Stanislav-Lapata it should show installed versions now.

I'm also working on bash for some unrelated reasons.
