### ISSUE TITLE
Add flag to specify tool dir for `rtx exec`

### ISSUE THREAD

**Issue by pzcfg** [jdx/rtx#977]
`rtx exec` has a `-C, --cd` option that lets you change the directory before executing the command, which initializes the tools for the current directory, then changes the dir and executes the command.

I'm hoping an option can be added that effectively `cd`s before the `rtx exec`, or tells rtx to search for `.tool-versions` from a specified directory instead of the current. Something sort of like:

```
rtx -x /path/to/tools -C /path/to/run -- some command

cd /path/to/tools
rtx hook-env ...
cd /path/to/run
some command
```

---

Also, side note, I noticed the help for the options are somewhat inconsistent:

```
Options:
  -c, --command <C>        Command string to execute
      --cd <CD>            Change to this directory before executing the command [short aliases: C]
  -j, --jobs <jobs>        Number of plugins and runtimes to install in parallel
```

Should the `[short aliases: C]` just be consolidated like the other options?

```
Options:
  -c, --command <C>        Command string to execute
  -C, --cd <CD>            Change to this directory before executing the command
  -j, --jobs <jobs>        Number of plugins and runtimes to install in parallel
```

**Comment by jdx** [comment]
I feel this would be better handled by an env var, maybe something like `RTX_DIR`

**Comment by jdx** [comment]
I'm actually thinking maybe this should be `RTX_CONFIG_ROOT` or something similar... though that might be a little confusing since we have `RTX_CONFIG_DIR` which is very different.

**Comment by pzcfg** [comment]
Maybe just `RTX_ROOT`? Or might that be confused with the install dir or somethingOn Nov 29, 2023, at 5:36 PM, jdx ***@***.***> wrote:﻿
I'm actually thinking maybe this should be RTX_CONFIG_ROOT or something similar... though that might be a little confusing since we have RTX_CONFIG_DIR which is very different.

**Comment by jdx** [comment]
notably in the codebase I call `RTX_DATA_DIR` the const variable `ROOT` but it does not appear I expose that to the user so that's something I can, and probably should, refactor away.

`RTX_ROOT` could work I think.

**Comment by jdx** [comment]
I'm looking at this again and I think it should have always just done both: set the tools in the new directory and move to that directory before running the command
