### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by jylenhofdecat** [jdx/rtx#992]
**Describe the bug**
Mismatch version between rtx doctor and apt version...

**To Reproduce**
Install rtx with apt

**Expected behavior**
rtx doctor should report the same version than apt

**`rtx doctor` output**

```shell
❯ rtx doctor
rtx version:
  2023.11.0 linux-x64 (2796c45 2023-11-02)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Thu, 2 Nov 2023 23:26:31 +0000
  Rust Version: rustc 1.73.0 (cc66ad468 2023-10-03)
  Profile: release

  <snip>

1 problem found:
new rtx version 2023.11.2 available, currently on 2023.11.0
```

**Additional context**
```shell
❯ apt info rtx
Package: rtx
Version: 2023.11.2
Priority: optional
```

**Comment by jdx** [comment]
You're executing an installation that was not installed via apt

**Comment by jylenhofdecat** [comment]
Found the culprit, you're right.... It was locally installed because of the previous bug on apt that I had opened. I installed the apt one, but didn't remove the other one
