### ISSUE TITLE
Relative `env_path` is not updated when changing into subdirectory in conjunction with poetry.

### ISSUE THREAD

**Issue by chronicc** [jdx/rtx#993]
**Describe the bug**
When using the `env_path` key in `.rtx.toml` with a relative path, changing into a subdirectory below the directory which contains `.rtx.toml`, the `PATH` is not updated to reflect the switch into the subdirectory. Hence the project binaries can not be found anymore.

**To Reproduce**
- Create a `.rtx.toml` file with following config:
```toml
env_path = [
  ".venv/bin"
]

[env]
# poetry
POETRY_ACTIVE="true"
POETRY_VIRTUALENVS_IN_PROJECT="true"
POETRY_VIRTUALENVS_PATH=".venv"
VIRTUAL_ENV=".venv"

# rtx
RTX_EXPERIMENTAL="true"
RTX_FETCH_REMOTE_VERSIONS_TIMEOUT="30s"

[tools]
poetry="1.6.1"
```
- Initialize the directory with poetry and install a package with a binary (e.g. ansible-builder).
- Create a subdirectory.
- Change into this subdirectory.
- Notice that running `ansible-builder` throws error `-l: .venv/bin/ansible-builder: No such file or directory`.
- Notice that running `rtx x -- ansible-builder` throws error `rtx "ansible-builder" couldn't exec process: No such file or directory`.
- Notice that the `PATH` variable still uses `.venv/bin` inside of the subdirectory.

**Expected behavior**
Whether rtx updates the `PATH` variable to include the path from the subdirectory (in this case `../.venv/bin` or the relative paths are transcribed to the absolute version of the directory location (e.g. `/home/user/path/to/dir/.venv/bin` which would be the preferred solution).

**`rtx doctor` output**

```
rtx version:
  2023.11.2 linux-x64 (5bbc727 2023-11-09)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL, SELF_UPDATE
  Built: Thu, 9 Nov 2023 18:36:52 +0000
  Rust Version: rustc 1.73.0 (cc66ad468 2023-10-03)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx data directory:
  /home/thomas/.local/share/rtx

rtx environment variables:
  RTX_EXPERIMENTAL=true
  RTX_FETCH_REMOTE_VERSIONS_TIMEOUT=30s
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "true", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /home/thomas/.config/rtx/config.toml
  /home/thomas/git/###/###/###/###/scripts/awx-ee-build/.python-version
  /home/thomas/git/###/###/###/###/scripts/awx-ee-build/.rtx.toml

plugins:
  bun      (core)
  deno     (core)
  go       (core)
  java     (core)
  node     (core)
  poetry   https://github.com/rtx-plugins/rtx-poetry.git#3d4c703
  python   (core)
  ruby     (core)

toolset:
  poetry@1.6.1, python@3.12.0

No problems found

```

**Additional context**
I found this problem in context to poetry but the underlying problem is how relative paths are handled which should be transcribed to absolute paths imho.

**Comment by jdx** [comment]
you need to explicitly make it a relative path with `./.venv/bin`
