### ISSUE TITLE
Make the executables' `RUNPATH` relative instead of absolute

### ISSUE THREAD

**Issue by sschuberth** [jdx/rtx#996]
Executables created by `rtx` seem to set the ELF's `RUNPATH` to an absolute path inside `$RTX_DATA_DIR/installs`, see e.g.

```
$ readelf -d ~/.local/share/rtx/installs/python/3.11.3/bin/python3.11

Dynamic section at offset 0x2dd8 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.11.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/sebastian/.local/share/rtx/installs/python/3.11.3/lib]
```

This hurts relocating e.g. ~/.local/share/rtx/installs/python to somewhere else as SO files would not be found anymore, also see #512.

To solve this, could `RUNPATH` be set to a relative path instead?

**Comment by jdx** [comment]
rtx does not create runtimes. That is done by python-build.

**Comment by sschuberth** [comment]
The same issue occurs e.g. with ruby, which is an rtx core plugin, or?

Anyway, instead of reaching out to each individual plugin authors, maybe rtx could do some post-processing on ELFs to consistently patch them to use relative `RUNPATH`s?

**Comment by jdx** [comment]
for ruby the issue is inside of ruby-build, not the core plugin

**Comment by sschuberth** [comment]
FYI, this is the post-processing I'm now doing:

```
# Patch the RUNPATH to be relative in order to make relocated executables work.
find ~/.local/share/rtx/installs -type f -executable -exec sh -c 'file $1 | grep -q " ELF "' sh {} \; -print \
    | xargs patchelf --set-rpath '$ORIGIN'/../lib
```

This works better than expected, so I'm going to close this.
